Repository Fusion-Power-Plant-Framework/bluemira, pull requests merged in 2024-02, with the labels that each got.

#2979 PROCESS - BM obsolete parameter names
  bluemira/codes/interface.py
  bluemira/codes/process/_setup.py
  bluemira/codes/process/_teardown.py
Labels: 📜 Papercut

#2980 Fixed broken conditional statements in ComponentPlotter so now chooses correct plotting option
  bluemira/display/plotter.py
  examples/geometry/plotting_tutorial.ex.py
  tests/display/test_plotter.py
Labels: 📜 Papercut

#2981 Add lower port tests
  bluemira/utilities/opt_variables.py
  eudemo/eudemo/maintenance/lower_port/duct_designer.py
  eudemo/eudemo_tests/maintenance/test_eq_port.py
  eudemo/eudemo_tests/maintenance/test_lower_port.py
  eudemo/eudemo_tests/maintenance/test_upper_port.py
Labels: EU-DEMO, tests, 📜 Papercut

#2996 🐛 Fix Zenodo submission
  .pre-commit-config.yaml
  CITATION.cff
Labels: quality, release, upstream

#2994 🐛 Fix codecov upload
  .github/workflows/ci.yml
Labels: continuous_integration

#2998 Papercut complete, xtest are no longer failing.
  bluemira/geometry/parameterisations.py
  tests/geometry/test_parameterisations.py
Labels: geometry

#2977 ⬆️ 👽 Bump PROCESS version
  bluemira/codes/process/_equation_variable_mapping.py
  bluemira/codes/process/_inputs.py
  bluemira/codes/process/_model_mapping.py
  data/reactors/EU-DEMO/systems_code/IN.DAT
  examples/data/codes/process/ST_IN.DAT
  scripts/install-process.sh
  tests/codes/process/test_data/IN.DAT
  tests/codes/process/test_data/MFILE.DAT
  tests/codes/process/test_template_builder.py
Labels: dependencies, upstream, python

#3013 📝 Plan update Q1 24
  README.md
  documentation/source/bluemira-roadmap-dark.svg
  documentation/source/bluemira-roadmap.svg
  documentation/source/introduction.rst
Labels: bluemira_strategy

#3019 🐛 Fix getting component manager type if annotations imported
  bluemira/base/reactor.py
Labels: bug

#3020 🐛 Remove outdated process switch
  eudemo/eudemo/radial_build.py
Labels: bug

#3032 Reactor config addition for handling path expansion
  bluemira/base/reactor_config.py
  eudemo/config/build_config.json
  tests/base/reactor_config/data/reactor_config.test.json
  tests/base/reactor_config/test_reactor_config.py
Labels: bug

#3036 Urgent fix coil type
  bluemira/base/constants.py
  bluemira/builders/pf_coil.py
  bluemira/equilibria/coils/__init__.py
  bluemira/equilibria/coils/_coil.py
  bluemira/equilibria/coils/_grouping.py
  bluemira/equilibria/equilibrium.py
  bluemira/equilibria/plotting.py
  bluemira/equilibria/positioner.py
  bluemira/fuel_cycle/analysis.py
  bluemira/fuel_cycle/lifecycle.py
  bluemira/fuel_cycle/tools.py
  bluemira/geometry/_pyclipper_offset.py
  bluemira/geometry/coordinates.py
  bluemira/geometry/tools.py
  bluemira/structural/element.py
  bluemira/structural/loads.py
  bluemira/structural/model.py
  eudemo/eudemo/pf_coils/builder.py
  eudemo/eudemo/power_cycle.py
  tests/base/test_constants.py
  tests/geometry/test_tools.py
Labels: bug
