Repository Fusion-Power-Plant-Framework/bluemira, pull requests merged in 2025-06, with the labels that each got.

#3915 🏗️ Qtapp robustness improvement
  bluemira/codes/_freecadapi.py
  bluemira/display/auto_config.py
  bluemira/utilities/tools.py
Labels: display

#3950 CAD to DAGMC example, with OpenMC run (using BM materials)
  .github/workflows/actions/build/action.yml
  .github/workflows/ci.yml
  .github/workflows/examples.yml
  bluemira/equilibria/equilibrium.py
  bluemira/radiation_transport/neutronics/dagmc/dagmc_converter_fast_ctd.py
  documentation/source/examples.rst
  eudemo/config/build_config.json
  eudemo/eudemo/reactor.py
  examples/design/optimised_reactor.ex.py
Labels: examples, neutronics

#3960 🐛 Fix sonarcloud codeqa
  bluemira/materials/material.py
  bluemira/radiation_transport/radiation_profile.py
Labels: quality

#3967 🎨 Name more constraints
  bluemira/builders/tf_coils.py
  bluemira/geometry/optimisation/_tools.py
  eudemo/eudemo/blanket/panelling/_opt_problem.py
  eudemo/eudemo/maintenance/upper_port.py
  examples/design/simple_reactor.ex.py
  examples/optimisation/geometry_optimisation.ex.py
Labels: optimisation

#3958 👷 Cache precommit
  .github/workflows/ci.yml
Labels: continuous_integration

#3977 👷 Run examples only on push to relevant branches
  .github/workflows/examples.yml
Labels: continuous_integration

#3976 👷 Update ruff check alias
  .pre-commit-config.yaml
Labels: continuous_integration, quality

#3984 🐛 Skip uv version for transient dependency pins
  .github/workflows/pin_dependencies.yml
Labels: dependencies, python

#3986 📌 Change default python version to 3.11
  .github/workflows/ci.yml
  .github/workflows/comments.yml
  scripts/install-conda.sh
Labels: continuous_integration, dependencies, python

#3975 🏷️ Typing improvements from ty
  bluemira/equilibria/analysis.py
  bluemira/equilibria/coils/_field.py
  bluemira/equilibria/coils/_grouping.py
  bluemira/equilibria/coils/_tools.py
  bluemira/equilibria/equilibrium.py
  bluemira/equilibria/flux_surfaces.py
  bluemira/equilibria/grid.py
  bluemira/equilibria/profiles.py
  bluemira/equilibria/solve.py
  bluemira/magnetostatics/fem_utils.py
  bluemira/radiation_transport/flux_surfaces_maker.py
  bluemira/radiation_transport/radiation_profile.py
  bluemira/radiation_transport/radiation_tools.py
Labels: quality

#3953 Fix_Bug_3949
  bluemira/equilibria/coils/_grouping.py
  bluemira/equilibria/coils/_tools.py
  examples/equilibria/quick_look_at_example_coilsets.ex.py
  tests/_helpers.py
  tests/equilibria/test_coils.py
  tests/equilibria/test_data/coilsets/DEMO-DN_coilset.json
  tests/equilibria/test_data/coilsets/DEMO-SN_coilset.json
  tests/equilibria/test_data/coilsets/ITER_coilset.json
Labels: equilibria, pf_coil
