Repository Fusion-Power-Plant-Framework/bluemira, pull requests merged in 2025-02, with the labels that each got.

#3796 💚 Unpin pyside
  requirements/conda.txt
Labels: continuous_integration, dependencies, python

#3795 🚨 Use biome for json files
  .pre-commit-config.yaml
Labels: continuous_integration, quality

#3800 Finalising tests to radiation_transport
  bluemira/radiation_transport/radiation_profile.py
  bluemira/radiation_transport/radiation_tools.py
  tests/radiation_transport/test_radiation_profile.py
Labels: radiation_transport, tests

#3815 TODO to NOTE
  bluemira/structural/transformation.py
Labels: quality

#3813 🐛 Fix pint warning
  bluemira/base/constants.py
Labels: base, bug

#3823 Use numba-scipy hash
  conda/environment.yml
  pyproject.toml
  requirements/conda.txt
  requirements/uv/all.txt
  requirements/uv/base.txt
  requirements/uv/develop.txt
  requirements/uv/examples.txt
Labels: dependencies, python

#3825 🐛 Fix h5py in conda build
  conda/environment.yml
  requirements/conda.txt
Labels: continuous_integration, dependencies, python

#3692 Eq analysis tools update
  bluemira/codes/plasmod/equilibrium_2d_coupling.py
  bluemira/display/plotter.py
  bluemira/equilibria/analysis.py
  bluemira/equilibria/coils/_field.py
  bluemira/equilibria/coils/_tools.py
  bluemira/equilibria/diagnostics.py
  bluemira/equilibria/equilibrium.py
  bluemira/equilibria/fem_fixed_boundary/fem_magnetostatic_2D.py
  bluemira/equilibria/find_legs.py
  bluemira/equilibria/optimisation/problem/_minimal_current.py
  bluemira/equilibria/physics.py
  bluemira/equilibria/plotting.py
  bluemira/equilibria/run.py
  bluemira/equilibria/solve.py
  bluemira/utilities/plot_tools.py
  bluemira/utilities/tools.py
  documentation/source/examples.rst
  eudemo/eudemo/equilibria/_designer.py
  examples/equilibria/anaylsis_toolbox_examples.ex.py
  examples/equilibria/coilset_opt_problem_tutorial.ex.py
  examples/equilibria/eudemo_2017.ex.py
  examples/equilibria/single_null.ex.py
  examples/equilibria/spherical_harmonic_approximation_basic_use.ex.py
  tests/equilibria/test_analysis.py
  tests/equilibria/test_equilibrium.py
  tests/equilibria/test_force_field.py
  tests/equilibria/test_optimisation.py
  tests/equilibria/test_st_equilibrium.py
Labels: enhancement, equilibria
